name: Labeler2
on: [check_run, check_suite, pull_request_review]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Merge pull requests
      uses: fmikina/automerge-action@v0.4.2
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
