name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Merge pull requests
      uses: pascalgn/automerge-action@v0.2.5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
