name: Labeler2

on:
  schedule:	
    - cron:  '*/5 * * * *'

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: Merge pull requests
      uses: fmikina/automerge-action@v0.5.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
